language: node_js # 언어

node_js:
    - 12

cache: npm

services:
    - docker

branches:
    only:
        - master
env:
    global:
        - DOCKER_USER=wltn3231
        - DOCKER_PASS=mypassword

jobs:
    include:
        - stage: "Tests"
          name: "Client Test"
          before_install:
              - cd ./client
          install:
              - npm install
          script:
              - npm run test
        - name: "Server Test"
          before_install:
              - cd ./server
          install:
              - npm install
          script:
              - echo head_branch
