language: node_js
node_js:
  - 12
cache: npm
script:
  - sudo cat /etc/docker/daemon.json
  - 'sudo cat /etc/docker/daemon.json | jq ''. + {"insecure-registries": ["45.119.146.88:5000"]}'' | sudo tee /etc/docker/daemon.json'
  - sudo cat /etc/docker/daemon.json
services:
  - docker
env:
  global:
    - REGISTRY=45.119.146.88:5000
    - DOCKER_USERNAME=cocode
    - DEPLOY_IP=45.119.146.88
    - secure: DxfO29Z5NFQu1x3UlLmrN1QF7EZ4IIv7kS65fWoNogccKh0GE7WLNhmXp9EcZL4/qhf8gLNzMPCYq1Y2Wsnjkxw5h3E0M4/LjWQAgw16iTnP5oTjAX87GwGpr2WwTNJhBl+dRylPiVvfPMhEKUHuVyPNl42kAfJSo54se0YX2Fes2twIiRzUH3mFRbmKEpp0lSO7Gq7+4Q2Gpq24+O/sQ80qnF+RmNhuSeD27qPpl1WNU550Dt4I6InshIv6H5RB1Fk47pg6K76Wx/xCVrPvo9xDwTNh6wukqiPU8Eo6WYyF9r471KUgDfpM5ecyrasFSuc+wN0RAtNSWOZJUL2kHi8v6TB0IEaQFez2TSJ4t8u+laJ9cS6GrLixPFXX6OLyzjd2JVh1QSIBrksfxTI5X/n2hfHsuX9q2j8ChQYHbtA5YHsh0hBNqO9sztt+0kEJVuEavY1Oufxs6HH20PKeAvL8Oh/AOnjuSPFizdKZf4cmT4OXNiiwGw5cuKJ8AER5fMxp8z/0rKKsFCdyTUmGCNnVhhewxth8p+edCD/bgLRewy9vM3RKvud6edz9Y8tavj85oRe9fAHvpmLIOy4SvUBZ12WQQzTL9jruuqB1k+/DRy4hOhsqVh7vIjvqe74Qa6JuojMezm4L3vl7qRaOXgNQdKG/Ugv2J1VAJ1Vdaog=
jobs:
  include:
    - stage: Deploy
      before_script:
        # - sudo cat /etc/docker/daemon.json
        # - 'sudo cat /etc/docker/daemon.json | jq ''. + {"insecure-registries": ["45.119.146.88:5000"]}'' | sudo tee /etc/docker/daemon.json'
        # - sudo cat /etc/docker/daemon.json
        # - sudo service docker restart
        # - sudo cat /etc/docker/daemon.json
        - sudo apt-get install sshpass
      script:
        - echo "deploy"
        - cd api-server
        - docker build -t "$REGISTRY"/cocode/api:1.0 .
        - docker images
        - docker push "$REGISTRY"/cocode/api:1.0
        - sshpass -p "$DEPLOY_PASSWORD" ssh -o StrictHostKeyChecking=no root@"$DEPLOY_IP" /root/practice-boilerplate-monorepo/script/deploy.sh "$DOCKER_USERNAME"
