language: node_js # 언어

node_js:
    - 12

cache: npm

services:
    - docker

branches:
    only:
        - master
env:
    global:
        - DOCKER_USER=wltn3231
        - DOCKER_PASS=mypassword

jobs:
    script:
        - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
        - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
    include:
        - stage: "Tests"
          name: "Client Test"
          before_install:
              - cd ./client
          install:
              - npm install
          script:
              - npm run test
        - name: "Server Test"
          before_install:
              - cd ./server
          install:
              - npm install
          script:
              - echo "server"
