language: node_js
node_js:
  - 12
cache: npm
services:
  - docker

jobs:
  include:
    - stage: Tests
      env:
        - SKIP_PREFLIGHT_CHECK=true
      name: Client Test
      script:
        - echo "client test"
    - name: API Server Test
      script:
        - echo "server test"

    - stage: Deploy
      name: Client Deploy
      script:
        - echo "client deploy"
    - name: API Server Deploy
      script:
        - echo "server deploy"
    # - stage: Tests
    #   env:
    #     - SKIP_PREFLIGHT_CHECK=true
    #   name: Cocode Client Test
    #   before_install:
    #     - cd ./cocode
    #   install:
    #     - yarn install
    #   script:
    #     - yarn jest
    # - name: API Server Test
    #   before_install:
    #     - cd ./api-server
    #   install:
    #     - npm install
    #   script:
    #     - npm run test
    # - stage: Deploy
    #   name: Deploy Client
    #   before_script:
    #     - cd ./cocode
    #     - echo "$DOCKER_PASSWORD" | docker login -u "${DOCKER_USERNAME}" --password-stdin
    #   script:
    #     - docker build -t wltn3231/test-client:v3 .
    #     - docker push wltn3231/test-client:v3
    # - name: Deploy Server
    #   before_script:
    #     - cd ./api-server
    #     - echo "$DOCKER_PASSWORD" | docker login -u "${DOCKER_USERNAME}" --password-stdin
    #   script:
    #     - docker build -t wltn3231/test-server:v3 .
    #     - docker push wltn3231/test-server:v3
