language: node_js
node_js:
  - 12
cache: npm
services:
  - docker
env:
  global:
    - DOCKER_USER=wltn3231
    - secure: fFstO4pSPcf6X9NJIExCMZjJJy0vEcP2gDBVdbocps/VMQaxKWMr0YlSA9k24HMH5z2fYd+KKAaPpCwh+2NX6xsfIrpEsuIrbZSg/TsEasOH0mRWe8ovXV8cFlgRHULk7dK7Hnv9altHJV4omnVGOPCZlAywhfhff076Jrnga/Z08+KEQ5E2Q7ZOFPZrGniQUw5aSGZAmCY+R4R3fGZJgwP5qFM+lPUVOLDktsxesHt+p387rlCSMDNYqVJyiWlEoHQKAXD9AXassSeWJL4xHyp9kr8IPmSubC/4rS2Aoj/CzUnkA3paj2ZmDEN5tpqM3p3L49MgTMQ24Qlt4KZ54WWkK5876b24aLzecCMsLY6jI/Q9vHg7oK4mvSKRm6b2/KYpTPgAVdLGm7BPYQRhKob0kiz7UygFil6gn4EQskxWzkNxxOMy6dpHVvLz1QUWMhPqjEEs+PlCKdwZp7wR26mLTOBthX1ZwuoMoUxb0NJzacf26DY8h5ETqo/w6Ccey4hEb0wwXItoI40t/bDqmLiDEk5DhLSeZmRz8J4pFy3aaFRTdMe0pS/8J+AQu+NJv9A9dpeu0xZJfgJ4MGS7TTGfXj/UpHwSLsMoZKf+dzih/tep83YqlUmvZYMtFlVLjPN44/4mQg2XjDUdHpKeP5b2n7ochGZ27kEgH1GXftY=
jobs:
  include:
    - stage: Test
      script:
        - echo "test"
    - stage: Deploy
      if: branch = master AND type = pull_request
      before_install:
        - openssl aes-256-cbc -K $encrypted_4f20d19946f1_key -iv $encrypted_4f20d19946f1_iv -in env.tar.enc -out env.tar -d
        - tar xvf env.tar
      install:
        - sudo apt-get install sshpass
      before_script:
        - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
        - export SERVICE=$TRAVIS_PULL_REQUEST_BRANCH
      script:
        - echo "deploy ${SERVICE} service"
        - cd "$SERVICE"
        - docker build -t "$DOCKER_USER"/"$SERVICE":1.0 .
        - docker tag "$DOCKER_USER"/"$SERVICE":1.0 "$DOCKER_USER"/"$SERVICE":latest
        - docker push "$DOCKER_USER"/"$SERVICE":latest && docker push "$DOCKER_USER"/"$SERVICE":1.0
        - |
          if [ "${SERVICE}" = "cocode" ]; then
              sshpass -p "${COCODE_PASSWORD}" ssh -o StrictHostKeyChecking=no root@"${COCODE_IP}" /root/practice-boilerplate-monorepo/script/deploy.sh "$SERVICE" "$COCODE_PORT"
          elif [ "${SERVICE}" = "api-server" ]; then
              sshpass -p "${API_SERVER_PASSWORD}" ssh -o StrictHostKeyChecking=no root@"${API_SERVER_IP}" /root/practice-boilerplate-monorepo/script/deploy.sh "$SERVICE" "$API_SERVER_PORT"
          else
              echo "${SERVICE} nono!"
          fi
