language: node_js
node_js:
  - 12
cache: npm
services:
  - docker
env:
  global:
    - REGISTRY=45.119.146.88:5000
    - DOCKER_USERNAME=cocode
    - DEPLOY_IP=45.119.146.88
    - secure: SG9i4vK9+tkObQoukgKF4Jk27L4ki9Vmf8pO4ZAOEzueHfwHrgqG4YZzg6YpY1jIs7TYb4dt7zWoSW6TZm933ZR3n6P26MZp/N/hlaSKFAsfI3NsJN4nZiMDM0TaEEjZMwQerWpfLBcyKh8HkKy30qEDVvaqg0Qd8XqVYF79wCpLKC4YEwVEGNR9uYsyZPBwFGcCIdT8EwqJAsZ64JwTNcJrj+Gqr+OgsNv7cwX15Gl7C3+bNOYUZPLpAzrVpl+vsKTNwWXGUelGGWFQF4m8YUrZ9ubgDZ6NiLsypTFi0Bc2XPjG0iGz04sK4O01CoXSXQxRqrjm1Mv1fpPppJwePIwGTs2wSngqh5sxADslYHR/SCzgb0otKGtD1Z2meOnXyZY3ICsprIo/ENP8VOXL1nDUK0pZ5aiVJhGZpJsXK3aQVvW/mlKI6/o8khUeFjHkFeNonmHUAZBaHimYuOru3MwTeUeS0l1eYrY7Y76GndUxGjv+ieLwn5JumR95147rLh1aRiABB/5ldmpGvCNsSel0i4Hf2jMBipjsVJN3bqAn7QtTCW7P6hkquUXes8cPO6wwzqQcF++iNlsZeG0j7OQnUU9B6VW6gohluInYj3FIFZJ5d5OoAtynPe6u5hnLFkeoq2HJ4jOr6mCOD3U5YX5GgLdyWpPvPpMLZI29/SI=

jobs:
  include:
    - stage: Deploy
      before_script:
        - sudo ./script/accept-http-in-docker.sh
        - sudo apt-get install sshpass
      script:
        - echo "deploy"
        - cd api-server
        - docker build -t "$REGISTRY"/cocode/api:1.0 .
        - docker images
        - docker push "$REGISTRY"/cocode/api:1.0
        - sshpass -p "$DEPLOY_PASSWORD" ssh -o StrictHostKeyChecking=no root@"$DEPLOY_IP"
          "touch /root/success"
